import { describe, expect, it } from "vitest";
import { scoreListing } from "@/lib/domain/scoring";
import { deduplicateByChecksum } from "@/lib/domain/deduplication";
import { evaluateSend } from "@/lib/email/policy";
import { followUpStopReason } from "@/lib/email/follow-up";
import { assertGenerationPermitted } from "@/lib/domain/permission";
import { classifyReplyDeterministically } from "@/lib/ai/replies";
import { assertGenerationTransition, canTransitionListing } from "@/lib/domain/transitions";
import { generationDecision } from "@/lib/domain/workflow";
import { verifyHmacSignature } from "@/lib/payments/provider";
import { createHmac } from "node:crypto";
const listing={externalId:"x",address:"1 Test",city:"Dayton",state:"OH",zip:"45342",price:575000,daysOnMarket:81,photoCount:32,priceReductionCount:1,has3DTour:false,hasVirtualTour:false,status:"ACTIVE" as const};
describe("lead scoring",()=>{it("scores deterministically and remains normalized",()=>{const result=scoreListing(listing);expect(result.score).toBe(95);expect(result.eligible).toBe(true);expect(result.reason).toContain("81 DOM")});it("rejects young and toured listings",()=>expect(scoreListing({...listing,daysOnMarket:20,has3DTour:true}).eligible).toBe(false))});
it("deduplicates image checksums",()=>expect(deduplicateByChecksum([{checksum:"a",n:1},{checksum:"a",n:2},{checksum:"b",n:3}])).toHaveLength(2));
const sendBase={email:"agent@example.invalid",confidence:"VERIFIED" as const,suppressed:false,hasReply:false,listingStatus:"ACTIVE",dailySent:0,domainDailySent:0,dailyLimit:30,domainLimit:3,mode:"AUTO" as const};
describe("outreach policy",()=>{it("never sends to suppressed contact",()=>expect(evaluateSend({...sendBase,suppressed:true}).allowed).toBe(false));it("enforces daily and domain caps",()=>{expect(evaluateSend({...sendBase,dailySent:30}).allowed).toBe(false);expect(evaluateSend({...sendBase,domainDailySent:3}).allowed).toBe(false)});it("requires verified business contact",()=>expect(evaluateSend({...sendBase,confidence:"UNKNOWN"}).allowed).toBe(false));it("does not send in dry run",()=>expect(evaluateSend({...sendBase,mode:"DRY_RUN"}).allowed).toBe(false))});
it("stops every follow-up after a reply",()=>expect(followUpStopReason({hasReply:true,unsubscribed:false,bounced:false,permissionGranted:false,manualStop:false,listingStatus:"ACTIVE"})).toBe("REPLIED"));
describe("permission gate",()=>{it("MUST NOT start generation without GRANTED permission",()=>expect(()=>assertGenerationPermitted("REQUESTED")).toThrow(/permission/i));it("requires review in REVIEW mode",()=>expect(generationDecision("GRANTED","REVIEW").humanReview).toBe(true))});
describe("reply parsing",()=>{it("immediately recognizes unsubscribe",()=>expect(classifyReplyDeterministically("Remove me from your list.").classification).toBe("UNSUBSCRIBE"));it("flags uncertain text",()=>expect(classifyReplyDeterministically("Maybe later").requiresHumanReview).toBe(true));it("recognizes explicit permission",()=>expect(classifyReplyDeterministically("Sure, go ahead").classification).toBe("PERMISSION_GRANTED"))});
it("verifies payment webhook signature",()=>{const secret="test-secret",payload='{"paid":true}';const sig=createHmac("sha256",secret).update(payload).digest("hex");expect(verifyHmacSignature(payload,sig,secret)).toBe(true);expect(verifyHmacSignature(payload,"bad",secret)).toBe(false)});
describe("state machines",()=>{it("rejects skipped generation steps",()=>expect(()=>assertGenerationTransition("PENDING","READY")).toThrow());it("allows valid generation step",()=>expect(()=>assertGenerationTransition("PENDING","PREPROCESSING")).not.toThrow());it("prevents sold listing reactivation",()=>expect(canTransitionListing("SOLD","ACTIVE")).toBe(false))});
